#%RAML 1.0
title: Customer Accounts API

traits:
  running-user:
    queryParameters:
      user:
        description: The person or system requesting data
        required: true
        type: string

types:
  CustomerAccount: !include /datatypes/CustomerAccountDataType.raml
  
/accounts:
  get:
    queryParameters:
      [running-user]
      accountType:
        required: false
        enum:
          - Personal
          - Business
      name:
        required: false
        type: string
    responses:
      200:
        body:
          application/json:
            type: CustomerAccount[]
            examples:
              output: !include /examples/CustomerAccountsResponseExample.raml

  post:
    queryParameters:
      user:
        description: The person or system requesting data
        required: true
        type: string
    body:
      application/json:
        type: CustomerAccount[]
        examples:
          output: !include /examples/CustomerAccountsRequestExample.raml
    responses:
      201:
        body:
          application/json:
            example:
              message: Accounts created