#%RAML 1.0
title: Customer Accounts API (Svoboda)

traits:
  client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string
    responses:
      401:
        description: Unauthorized, The client_id or client_secret are not valid or the client does not have access.
      429:
        description: The client used all of its request quota for the current period.
      500:
        description: An error occurred, see the specific message (Only if it is a WSDL endpoint).
      503:
        description: Contracts Information Unreachable.
  running-user:
    queryParameters:
      user:
        description: The person or system requesting data
        required: true
        type: string
        default: System

types:
  CustomerAccount: !include /datatypes/CustomerAccount.raml
  CustomerAccountType: !include /datatypes/CustomerAccountType.raml
  
/accounts:
  is: [running-user,client-id-required]
  get:
    queryParameters:
      accountType:
        required: false
        type: CustomerAccountType
      name:
        required: false
        type: string
    responses:
      200:
        body:
          application/json:
            type: CustomerAccount[]
            examples:
              output: !include /examples/CustomerAccountsResponseExample.raml

  post:
    queryParameters:
      user:
        description: The person or system requesting data
        required: true
        type: string
    body:
      application/json:
        type: CustomerAccount[]
        examples:
          input: !include /examples/CustomerAccountsRequestExample.raml
    responses:
      201:
        body:
          application/json:
            example:
              message: Accounts created
              
  /{ID}:
    is: [running-user,client-id-required]
    get:        
      responses:
        200:
          body:
            application/json:
              type: CustomerAccount
              examples:
                output: !include /examples/CustomerAccountIdResponseExample.raml
        404:
          body:
            application/json:
              example:
                message: Account not found