#%RAML 1.0
title: Customer Accounts API

/accounts:
  get:
    queryParameters:
      Requestor:
        description: The person or system requesting data
        required: true
        type: string
      Account Type:
        required: false
        enum:
          - Personal
          - Business
      Customer Name:
        required: false
        type: string