#%RAML 1.0 NamedExample
value:

  -
    ID: 1
    name: 'Fredrick Flintstone'
    type: 'Personal'
    address: '2 Rubble Way, Bedrock, New Jersey 18275'
    airMiles: 5000000
    creationDate: 2023-05-23T00:00:00.000-0400