#%RAML 1.0 NamedExample
value:
  -
    name: Barney Rubble
    accountType: Personal
    address: 3 Rubble Way,Bedrock,New Jersey,18275,USA
    airMiles: 5
  -
    name: Boulder Gravel Co
    accountType: Business
    address: 54321 GreenSt,Boulder,Colorado,82433,USA
    airMiles: 1000