#%RAML 1.0 NamedExample
value:
  -
    ID: 1
    name: Fredrick Flintstone
    accountType: Personal
    address: 2 Rubble Way,Bedrock,New Jersey,18275,USA
    airMiles: 5000
    creationDate: 2023-05-23T00:00:00.000Z
  -
    ID: 2
    name: Spacely Sprockets
    accountType: Business
    address: 12345 GreenSt,Boulder,Colorado,82433,USA
    airMiles: 5000000
    creationDate: 2023-05-23T00:00:00.000Z